apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  selector:
    app: mq
  ports:
  - name: port1
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: port2
    protocol: TCP
    port: 15672
    targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
      - name: mq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
