apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-ui-deployment
  labels:
    app: qa-ui
spec:
  selector:
    matchLabels:
      app: qa-ui
  template:
    metadata:
      labels:
        app: qa-ui
    spec:
      containers:
      - name: qa-ui
        image: qa-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: qa-ui
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: qa-ui
